name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome and thank you for providing feedback to our learning RPG development! Contributions like these are what help open-source communities thrive. We will review this issue and respond when available to do so. You are awesome!'
        pr-message: 'Welcome and thank you! Contributions like these are what help open-source communities thrive. We will review this pull request and respond when available to do so. You are awesome!'
